dir:
  dataset: '../datasets/TIMIT/' # dataset directory
  models: 'models/' # for storing models
  plots: 'plots/' # for plots
  pickle: 'pickle/' # pickle dumps root path

train:

  batch_size: 1
  
  epochs: 1500 #total no. of epochs to train
  
  test_per_epoch: 0 #test per epoch i.e. how many times in ONE epoch
  test_every_epoch: 25 #after how many epochs
  print_per_epoch: 3 #print loss function how often in each epoch
  save_every: 50 #save models after how many epochs
  plot_every: 25 #save plots for test loss/train loss/accuracy

  resume: True #resume training from saved model
 
  loss_func: 'CTC' #loss function 
  optim: 'Adam' #optimiser to speed up training
  lr: 0.001 #learning rate

test:

  batch_size: 50


n_fbank: 40 # 40 for fitlerbank energies
n_mfcc: 39 # 39 for MFCC energies
window_size: 0.025 #25 milliseconds
window_step: 0.010 #10 ms
num_phones: 39 #39 phone labels

rnn: 'customLSTM'
hidden_dim: 384 # 384 for best GRU
num_layers: 5
grad_clip: 3
weighted_loss: False
std_multiplier: 5
bidirectional: True
cuda: True #whether to use NVIDIA cuda

decode_type: 'max' #max or CTC
gen_template: False
infer_mode: 'group' # group or indi
prob_thesh_const: 10 #replace 0 in substitution matrix with min/this value